spring:
  profiles: default
  datasource:
    url: jdbc:postgresql://localhost:5432/moneer
    username: ahmad
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
     ddl-auto: 'create'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

