CREATE TABLE BOOKS (
    ID INT PRIMARY KEY,
    TITLE VARCHAR(255),
    AUTHOR VARCHAR(255),
    EDITOR VARCHAR(255),
    RELEASE_DATE DATE,
    EDITION INT,
    PUBLISHER VARCHAR(255),
    COVER_IMAGE VARCHAR(255),
    DESCRIPTION TEXT,
    VOLUME_NUMBER INT,
    PAGES_COUNT INT
);